image: ubuntu:latest
stages:
  - deploy

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - find ./src/main/resources/templates/index.html
  artifacts:
    paths:
    - public
  only:
  - master
